/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AnimationInput: typeof import('./components/AnimationInput.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    BackButton: typeof import('./components/BackButton.vue')['default']
    VDialog: typeof import('./components/VDialog.vue')['default']
    VIcon: typeof import('./components/VIcon.vue')['default']
    CabinetDoor: typeof import('./components/TheMultiDoor/CabinetDoor.vue')['default']
    CardAuth: typeof import('./components/CardAuth.vue')['default']
    CarrierCountStatistics: typeof import('./components/CarrierCountStatistics.vue')['default']
    CarrierTable: typeof import('./components/CarrierTable.vue')['default']
    CheckPanel: typeof import('./components/CheckPanel.vue')['default']
    DeviceStatus: typeof import('./components/DeviceStatus.vue')['default']
    FingerAuth: typeof import('./components/FingerAuth.vue')['default']
    LockStateDialog: typeof import('./components/LockStateDialog.vue')['default']
    MultiDoorPanel: typeof import('./components/MultiDoorPanel.vue')['default']
    NetworkStateDialog: typeof import('./components/NetworkStateDialog.vue')['default']
    PasswordAuth: typeof import('./components/PasswordAuth.vue')['default']
    RfidStateDialog: typeof import('./components/RfidStateDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetCardDialog: typeof import('./components/SetCardDialog.vue')['default']
    SetFingerDialog: typeof import('./components/SetFingerDialog.vue')['default']
    SetPasswordDialog: typeof import('./components/SetPasswordDialog.vue')['default']
    StartButton: typeof import('./components/StartButton.vue')['default']
    TheMenuDrawer: typeof import('./components/TheMenuDrawer.vue')['default']
    TheMultiDoor: typeof import('./components/TheMultiDoor/index.vue')['default']
    TheSingleDoor: typeof import('./components/TheSingleDoor.vue')['default']
    VerifyIdentity: typeof import('./components/VerifyIdentity.vue')['default']
    WarningDialog: typeof import('./components/WarningDialog.vue')['default']
  }
}
