/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AlarmRecordCard: typeof import('./components/AlarmRecordCard.vue')['default']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AnimationInput: typeof import('./components/AnimationInput.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    BackButton: typeof import('./components/BackButton.vue')['default']
    BaseLoading: typeof import('./components/BaseLoading.vue')['default']
    DeviceStatus: typeof import('./components/DeviceStatus.vue')['default']
    NetworkStateDialog: typeof import('./components/NetworkStateDialog.vue')['default']
    RfidStateDialog: typeof import('./components/RfidStateDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewDetailButton: typeof import('./components/ViewDetailButton.vue')['default']
  }
}
