/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activate': RouteRecordInfo<'/activate', '/activate', Record<never, never>, Record<never, never>>,
    '/alarm': RouteRecordInfo<'/alarm', '/alarm', Record<never, never>, Record<never, never>>,
    '/alarm-multiple': RouteRecordInfo<'/alarm-multiple', '/alarm-multiple', Record<never, never>, Record<never, never>>,
    '/alarm-record': RouteRecordInfo<'/alarm-record', '/alarm-record', Record<never, never>, Record<never, never>>,
    '/check': RouteRecordInfo<'/check', '/check', Record<never, never>, Record<never, never>>,
    '/detail/[id]': RouteRecordInfo<'/detail/[id]', '/detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/index copy': RouteRecordInfo<'/index copy', '/index copy', Record<never, never>, Record<never, never>>,
    '/multiple-alarm/': RouteRecordInfo<'/multiple-alarm/', '/multiple-alarm', Record<never, never>, Record<never, never>>,
    '/record-detail': RouteRecordInfo<'/record-detail', '/record-detail', Record<never, never>, Record<never, never>>,
    '/rfid-record': RouteRecordInfo<'/rfid-record', '/rfid-record', Record<never, never>, Record<never, never>>,
  }
}
