// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ActionPanel: typeof import('./src/components/ActionPanel.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    BaseAlert: typeof import('./src/components/BaseAlert/index.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    CardAuth: typeof import('./src/components/CardAuth.vue')['default']
    CheckPanel: typeof import('./src/components/CheckPanel.vue')['default']
    DeviceStatus: typeof import('./src/components/DeviceStatus.vue')['default']
    DoorInfoPanel: typeof import('./src/components/DoorInfoPanel.vue')['default']
    FingerAuth: typeof import('./src/components/FingerAuth.vue')['default']
    LockStateDialog: typeof import('./src/components/LockStateDialog.vue')['default']
    NetworkStateDialog: typeof import('./src/components/NetworkStateDialog.vue')['default']
    PasswordAuth: typeof import('./src/components/PasswordAuth.vue')['default']
    RfidStateDialog: typeof import('./src/components/RfidStateDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetCardDialog: typeof import('./src/components/SetCardDialog.vue')['default']
    SetFingerDialog: typeof import('./src/components/SetFingerDialog.vue')['default']
    SetPasswordDialog: typeof import('./src/components/SetPasswordDialog.vue')['default']
    TheLogin: typeof import('./src/components/TheLogin.vue')['default']
    TheMain: typeof import('./src/components/TheMain.vue')['default']
    TheMainPanel: typeof import('./src/components/TheMainPanel.vue')['default']
    ViewDocumentDialog: typeof import('./src/components/ViewDocumentDialog.vue')['default']
    WarningDialog: typeof import('./src/components/WarningDialog.vue')['default']
  }
}
