// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ActionPanel: typeof import('./src/components/ActionPanel.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AnimationInput: typeof import('./src/components/AnimationInput.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    BaseAlert: typeof import('./src/components/BaseAlert/index.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseDialog: typeof import('./src/components/BaseDialog.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    CardAuth: typeof import('./src/components/CardAuth.vue')['default']
    CarrierCountStatistics: typeof import('./src/components/CarrierCountStatistics.vue')['default']
    CheckPanel: typeof import('./src/components/CheckPanel.vue')['default']
    copy: typeof import('./src/components/DeviceStatus copy.vue')['default']
    DeviceStatus: typeof import('./src/components/DeviceStatus.vue')['default']
    DocumentTable: typeof import('./src/components/DocumentTable.vue')['default']
    FingerAuth: typeof import('./src/components/FingerAuth.vue')['default']
    LockStateDialog: typeof import('./src/components/LockStateDialog.vue')['default']
    MultiDoorPanel: typeof import('./src/components/MultiDoorPanel.vue')['default']
    NetworkStateDialog: typeof import('./src/components/NetworkStateDialog.vue')['default']
    PasswordAuth: typeof import('./src/components/PasswordAuth.vue')['default']
    RfidStateDialog: typeof import('./src/components/RfidStateDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetCardDialog: typeof import('./src/components/SetCardDialog.vue')['default']
    SetFingerDialog: typeof import('./src/components/SetFingerDialog.vue')['default']
    SetPasswordDialog: typeof import('./src/components/SetPasswordDialog.vue')['default']
    SingleDoorPanel: typeof import('./src/components/SingleDoorPanel.vue')['default']
    StartButton: typeof import('./src/components/StartButton.vue')['default']
    TheLogin: typeof import('./src/components/TheLogin.vue')['default']
    VerifyIdentity: typeof import('./src/components/VerifyIdentity/index.vue')['default']
    WarningDialog: typeof import('./src/components/WarningDialog.vue')['default']
  }
}
